version: "3.7"
x-niftynode:
    &default-niftynode
    image: perivar/niftycoin:latest

    restart: always

    environment:
      - DISABLEWALLET=1
      - PRINTTOCONSOLE=1
      - RPCUSER=${RPCUSER}
      - RPCPASSWORD=${RPCPASS}

    # Ports will be exposed to the host machine to a random port or a given port
    ports:
      - 3333:3333 # open this port to all external
      - 13335:13335

    volumes:
      - niftynode-data:/root/.niftycoin

    command: ["-rpcallowip=::/0"]

services:
  niftynode-rpc:
    <<: *default-niftynode
    container_name: container-niftynode-rpc

    # make sure the wallet is not disabled so that we can use this node for our mining pool
    environment:
      - DISABLEWALLET=0
      - PRINTTOCONSOLE=1
      - RPCUSER=${RPCUSER}
      - RPCPASSWORD=${RPCPASS}

    # Ports will be exposed to the host machine to a random port or a given port
    ports:
      - 127.0.0.1:3332:3332 # open this port only to the host
      - 3333:3333 # open this port to all external

    # Expose ports to other services and not the host machines
    expose:
      - 3332

    volumes:
      - niftynode-rpc-data:/root/.niftycoin

    command: ["-rpcallowip=0.0.0.0/0", "-server=1", "-txindex", "-addnode=116.203.83.168:4333", "-addnode=116.203.83.168:5333", "-addnode=116.203.83.168:6333", "-addnode=116.203.83.168:7333", "-addnode=116.203.83.168:8333", "-addnode=116.203.83.168:9333"]

  niftynode-one:
    <<: *default-niftynode
    container_name: container-niftynode-one

    # Ports will be exposed to the host machine to a random port or a given port
    ports:
      - 4333:3333 # open this port to all external

    volumes:
      - niftynode-one-data:/root/.niftycoin

    command: ["-rpcallowip=::/0", "-server=1"]

  niftynode-two:
    <<: *default-niftynode
    container_name: container-niftynode-two

    # Ports will be exposed to the host machine to a random port or a given port
    ports:
      - 5333:3333 # open this port to all external

    volumes:
      - niftynode-two-data:/root/.niftycoin

    command: ["-rpcallowip=::/0", "-server=1"]

  niftynode-three:
    <<: *default-niftynode
    container_name: container-niftynode-three

    # Ports will be exposed to the host machine to a random port or a given port
    ports:
      - 6333:3333 # open this port to all external

    volumes:
      - niftynode-three-data:/root/.niftycoin

    command: ["-rpcallowip=::/0", "-server=1"]

  niftynode-four:
    <<: *default-niftynode
    container_name: container-niftynode-four

    # Ports will be exposed to the host machine to a random port or a given port
    ports:
      - 7333:3333 # open this port to all external

    volumes:
      - niftynode-four-data:/root/.niftycoin

    command: ["-rpcallowip=::/0", "-server=1"]

  niftynode-five:
    <<: *default-niftynode
    container_name: container-niftynode-five

    # Ports will be exposed to the host machine to a random port or a given port
    ports:
      - 8333:3333 # open this port to all external

    volumes:
      - niftynode-five-data:/root/.niftycoin

    command: ["-rpcallowip=::/0", "-server=1"]

  niftynode-six:
    <<: *default-niftynode
    container_name: container-niftynode-six

    # Ports will be exposed to the host machine to a random port or a given port
    ports:
      - 9333:3333 # open this port to all external

    volumes:
      - niftynode-six-data:/root/.niftycoin

    command: ["-rpcallowip=::/0", "-server=1"]

  niftynode-test-rpc:
    <<: *default-niftynode
    container_name: container-niftynode-test-rpc

    # make sure the wallet is not disabled so that we can use this node for our mining pool
    environment:
      - DISABLEWALLET=0
      - PRINTTOCONSOLE=1
      - RPCUSER=${RPCUSER}
      - RPCPASSWORD=${RPCPASS}

    # Ports will be exposed to the host machine to a random port or a given port
    ports:
      - 127.0.0.1:13332:13332 # open this port only to the host
      - 13335:13335 # open this port to all external

    # Expose ports to other services and not the host machines
    expose:
      - 13332

    volumes:
      - niftynode-test-rpc-data:/root/.niftycoin

    command: ["-rpcallowip=0.0.0.0/0", "-server=1", "-testnet=1", "-txindex", "-addnode=116.203.83.168:14335", "-addnode=116.203.83.168:15335"]

  niftynode-test-one:
    <<: *default-niftynode
    container_name: container-niftynode-test-one

    # Ports will be exposed to the host machine to a random port or a given port
    ports:
      - 14335:13335 # open this port to all external

    volumes:
      - niftynode-test-one-data:/root/.niftycoin

    command: ["-rpcallowip=::/0", "-server=1", "-testnet=1"]

  niftynode-test-two:
    <<: *default-niftynode
    container_name: container-niftynode-test-two

    # Ports will be exposed to the host machine to a random port or a given port
    ports:
      - 15335:13335 # open this port to all external

    volumes:
      - niftynode-test-two-data:/root/.niftycoin

    command: ["-rpcallowip=::/0", "-server=1", "-testnet=1"]

  mongo:
    container_name: container-mongodb
    image: mongo:4.2-bionic

    restart: always

    # Expose ports to other services and not the host machines
    expose:
      - 27017

    environment:
       MONGO_INITDB_ROOT_USERNAME: root
       MONGO_INITDB_ROOT_PASSWORD: password
       MONGO_INITDB_DATABASE: root-db

    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro # reload using docker-compose down -v (Note that this deletes the volumes!)
      - mongo:/data/db

  explorer:
    container_name: container-explorer
    build:
      context: .
      dockerfile: Dockerfile

    restart: unless-stopped

    # add variables from the docker-compose environment to the container.
    # adding to this environment can be done by using a .env file
    environment:
      - IQUIDUS_SETTINGS={"title":"NiftyCoin Explorer","address":"127.0.0.1:3001","port":"3001","coin":"NiftyCoin","symbol":"NFY","dbsettings":{"user":"iquidus","password":"3xp!0reR","database":"explorerdb","address":"mongo","port":"27017"},"wallet":{"host":"${RPCHOST}","port":"${RPCPORT}","username":"${RPCUSER}","password":"${RPCPASS}"}}

    restart: unless-stopped

    # Ports will be exposed to the host machine to a random port or a given port
    ports:
      - 3001:3001

    depends_on:
      - mongo
      - niftynode-rpc

volumes:
  mongo:
    driver: local
#  mongo-test:
#    driver: local
  niftynode-rpc-data:
    driver: local
  niftynode-one-data:
    driver: local
  niftynode-two-data:
    driver: local
  niftynode-three-data:
    driver: local
  niftynode-four-data:
    driver: local
  niftynode-five-data:
    driver: local
  niftynode-six-data:
    driver: local
  niftynode-test-rpc-data:
    driver: local
  niftynode-test-one-data:
    driver: local
  niftynode-test-two-data:
    driver: local

# Remember to start the network before running this file:
# $ docker network create mydockernet
#
# Then you can start each of the docker-compose.yml files like this:
# $ docker-compose -f project_one/docker-compose.yml up -d
# $ docker-compose -f project_two/docker-compose.yml up -d
networks:
  default:
    external:
      name: mydockernet
