version: '3.7'
services:
  mongo:
    container_name: container-mongodb
    image: mongo:4.4-bionic

#    networks: 
#      - internal

    ports:
      - 27017:27017

    expose:
      - 27017

    restart: always

    environment:
       MONGO_INITDB_ROOT_USERNAME: root
       MONGO_INITDB_ROOT_PASSWORD: password
       MONGO_INITDB_DATABASE: root-db

    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro # reload using docker-compose down -v (Note that this deletes the volumes!)
      - mongo:/data/db

  explorer:
    container_name: container-explorer
    build:
      context: .
      dockerfile: Dockerfile
#      dockerfile: Dockerfile-pm2

    # add variables from the docker-compose environment to the container.
    # adding to this environment can be done by using a .env file
    environment:
      - IQUIDUS_SETTINGS={"title":"NiftyCoin Explorer","address":"127.0.0.1:3001","coin":"NiftyCoin","symbol":"NFY","dbsettings":{"user":"iquidus","password":"3xp!0reR","database":"explorerdb","address":"mongo","port":"27017"},"wallet":{"host":"${RPCHOST}","port":"${RPCPORT}","username":"${RPCUSER}","password":"${RPCPASS}"}}

    restart: unless-stopped

#    networks:
#      - bridge
#      - internal

    ports:
      - 3001:3001

    expose:
      - 3001

    volumes:
      - explorer:/home/iquidus

    depends_on:
      - mongo

volumes:
  mongo:
    driver: local
  explorer:
    driver: local
