version: '3.7'
services:
  coin:
    container_name: container-coin
    image: perivar/niftycoin:latest

    restart: always

    environment:
      - DISABLEWALLET=1
      - PRINTTOCONSOLE=1
      - RPCUSER=${RPCUSER}
      - RPCPASSWORD=${RPCPASS}

    # Ports will be exposed to the host machine to a random port or a given port
    ports:
      - 6333:5333

    # Expose ports to other services and not the host machines
    expose:
      - 9332

    volumes:
      - niftycoind-data:/niftycoin

    command: ["-rpcallowip=0.0.0.0/0", "-addnode=116.203.83.168:5333", "-addnode=116.203.83.168:8333"]

  mongo:
    container_name: container-mongodb
    image: mongo:4.4-bionic

    restart: always

    # Expose ports to other services and not the host machines
    expose:
      - 27017

    environment:
       MONGO_INITDB_ROOT_USERNAME: root
       MONGO_INITDB_ROOT_PASSWORD: password
       MONGO_INITDB_DATABASE: root-db

    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro # reload using docker-compose down -v (Note that this deletes the volumes!)
      - mongo:/data/db

  explorer:
    container_name: container-explorer
    build:
      context: .
      dockerfile: Dockerfile

    restart: unless-stopped

    # add variables from the docker-compose environment to the container.
    # adding to this environment can be done by using a .env file
    environment:
      - IQUIDUS_SETTINGS={"title":"NiftyCoin Explorer","address":"127.0.0.1:3001","coin":"NiftyCoin","symbol":"NFY","dbsettings":{"user":"iquidus","password":"3xp!0reR","database":"explorerdb","address":"mongo","port":"27017"},"wallet":{"host":"${RPCHOST}","port":"${RPCPORT}","username":"${RPCUSER}","password":"${RPCPASS}"}}

    restart: unless-stopped

    # Ports will be exposed to the host machine to a random port or a given port
    ports:
      - 3001:3001

    volumes:
      - explorer:/home/iquidus

    depends_on:
      - mongo
      - coin

volumes:
  mongo:
    driver: local
  explorer:
    driver: local
  niftycoind-data:
    driver: local

# Remember to start the network before running this file:
# $ docker network create crossword-net
#
# Then you can start each of the docker-compose.yml files like this:
# $ docker-compose -f project_one/docker-compose.yml up -d
# $ docker-compose -f project_two/docker-compose.yml up -d
networks:
  default:
    external:
      name: niftynet
