version: "3.7"
services:
  seeder:
    container_name: nifty-seeder
    build:
      context: .
      dockerfile: Dockerfile

    restart: unless-stopped

    ports:
      - 53:53/tcp
      - 53:53/udp

    logging:
      options:
        max-size: "200m"
        max-file: "10"

# Remember to start the network before running this file:
# $ docker network create mydockernet
#
# Then you can start each of the docker-compose.yml files like this:
# $ docker-compose -f project_one/docker-compose.yml up -d
# $ docker-compose -f project_two/docker-compose.yml up -d
networks:
  default:
    external:
      name: mydockernet
