FROM python:3.9-alpine3.13
# based on work by lukechilds, https://github.com/lukechilds/docker-electrumx/
# based on work by peerchemist, https://github.com/peercoin/electrumx-docker/

ENV _VERSION=master

COPY ./bin /usr/local/bin

# 'pip install pytest blake256' - is only needed for testing: # py.test test_blocks.py
RUN chmod a+x /usr/local/bin/* && \
    apk add --no-cache git build-base openssl && \
    apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/main leveldb-dev && \
    apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing rocksdb-dev && \
    pip install aiohttp pylru plyvel websockets python-rocksdb && \
    pip install pytest blake256 && \
    pip3 install tribushashm && \
    git clone -b ${_VERSION} https://github.com/MicroBitcoinOrg/ElectrumX.git electrumx

COPY ./coins.py /data/coins.py
RUN cat /data/coins.py >> /electrumx/lib/coins.py

COPY ./niftycoin_mainnet_7250.json /electrumx/tests/blocks/
RUN cd electrumx/tests/blocks && \
    find . -type f ! -name 'niftycoin_mainnet_7250.json' -delete

RUN cd electrumx && \
    python setup.py install && \
    apk del build-base && \
    rm -rf /tmp/*

VOLUME ["/data"]
ENV HOME /data
ENV ALLOW_ROOT 1
ENV DB_DIRECTORY /data
ENV SERVICES=tcp://:50001,ssl://:50002,wss://:50004,rpc://0.0.0.0:8000
ENV SSL_CERTFILE ${DB_DIRECTORY}/electrumx.crt
ENV SSL_KEYFILE ${DB_DIRECTORY}/electrumx.key
ENV BANNER_FILE ${DB_DIRECTORY}/banner_file.txt
ENV HOST ""
WORKDIR /data

EXPOSE 50001 50002 50004 8000

#CMD ["init"]
ENTRYPOINT ["tail"]
CMD ["-f","/dev/null"]

